<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br>
            <br>
            <br>
            <h1>Conócenos</h1>
            <br>
            <br>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <img src="img/Mision.jpg" class="img-fluid">
                        <h3>Misión</h3>
                        <p>Brindar un servicio de atención psicológica de calidad, ético y profesional a la comunidad estudiantil y docente de la Universidad Tecnológica Fidel Velázquez, con la finalidad de satisfacer sus necesidades socioemocionales, fortalecer su salud mental e influir positivamente en la permanencia académica y laboral, previniendo la deserción escolar</p>
                    </div>
                    <div class="col-md-4">
                        <img src="img/Vision.jpg" class="img-fluid">
                        <h3>Visión</h3>
                        <p>Ser reconocidos como un espacio  de referencia que brinda atención psicológica en  nivel de educación superior, caracterizado por la innovación, excelencia y profesionalismo  en sus servicios. Aspiramos a consolidar una comunidad educativa emocionalmente saludable, donde cada estudiante y docente cuente con las herramientas necesarias para su desarrollo integral, contribuyendo así a formar profesionales adaptativos y autorregulados que impacten positivamente en la sociedad.</p>
                    </div>
                    <div class="col-md-4">
                        <img src="img/Filosofia.jpg" class="img-fluid">
                        <h3>Filosofía</h3>
                        <p>Brindar un servicio de calidad, en apego a los derechos humanos, con los principios de respeto inclusión, confidencialidad y eficiencia. </p>
                    </div>                    
                </div>
                <br>
                <br>
                <div class="col-md-12 mx-auto text-center">
                    <h3>¿Dónde nos ubicamos?</h3>
                    <div>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d939.5839709059005!2d-99.33880073441016!3d19.61293293167953!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d21989eadbcac9%3A0x92505b39e9cbcaf4!2sAtenci%C3%B3n%20Psicol%C3%B3gica%20UTFV!5e0!3m2!1ses-419!2smx!4v1751593086229!5m2!1ses-419!2smx" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                    <br>
                    <p style="font-size: small;">
                        <b>19.612952, -99.338154</b>
                        <br>
                        Emiliano Zapata S/N, El Trafico, 54400 Cdad. Nicolás Romero, Méx
                        <br>
                        <a href="https://maps.app.goo.gl/tV1X4uwWEfFUpdWf6">https://maps.app.goo.gl/tV1X4uwWEfFUpdWf6</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>