<!-- Inicia Footer -->
<footer class="bg-dark text-white pt-5 pb-4 px-5">
    <div class="container text-center text-md-start">
        <div class="row text-center text-md-start">

            <!-- Columna 1: Información de la empresa -->
            <div class="col-md-4 mx-auto mt-3">
                <h6 class="mb-4 font-weight-bold text-success">El área de atención psicológica de la UTFV busca...</h6>
                <p class="text-left" style="font-size: .8em;";>Ofrecer una plataforma digital accesible, intuitiva y funcional que permita a los estudiantes de la UTFV acceder de forma rápida y sencilla a los servicios gratuitos ofrecidos por el Área de Atención Psicológica. Este espacio busca promover el bienestar emocional y psicológico de los estudiantes, fomentando el autocuidado y facilitando el acceso a recursos de apoyo.</p>
            </div>

            <!-- Columna 2: Enlaces útiles -->
            <div class="col-md-4  mx-auto mt-3">
                <h6 class="mb-4 font-weight-bold text-success">Mapa de Sitio Web</h6>
                <div class="centrado-h-v ">
                    <ul style="text-align: left; font-size: .8em;">
                        <li><a href="#">Inicio</a></li>
                        <li><a href="#">Conocenos</a></li>
                        <li><a href="#">Iniciar sesión</a></li>
                        <li><a href="#">Regístrate</a></li>
                        <li><a href="#">contactanos</a></li>
                    </ul>
                </div>
                <br>
                <h6 class="mb-4 font-weight-bold text-success">Datos de contacto:</h6>
                <div class="centrado-h-v ">                    
                    <p class="text-left" style="font-size: .8em;";>Contáctanos: 5526493159 EXT: 297
                        <br>
                        Correo: depto.psicologia@utfv.edu.mx
                    </p>
                </div>
            </div>

            <!-- Columna 3: Contacto -->
            <div class="col-md-4  mx-auto mt-3">
                <h6 class="mb-4 font-weight-bold text-success">¡Síguenos en Redes Sociales!</h6>
                <p class="text-left" style="font-size: .8em;";>Conéctate con nosotros y mantente al día con las últimas noticias, eventos y recursos. Sé parte de nuestra comunidad y accede a contenido exclusivo para tu bienestar.</p>
            </div>

        </div>
        <hr class="mb-4">
        <div class="row align-items-center">
            <div class="col-12">
                <p>
                    © 2025 Todos los derechos reservados: Atención Psicológica - UTFV <a href="https://atenpsicologica.utfv.net/" class="footer-link"><strong>atenpsicologica.utfv.net</strong></a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- Inicia Footer -->