<!-- Inicia Video -->
<div class="containe-fluid">
    <header>
        <div class="overlay"></div>
        <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
            <source src="videos/videoIndex.mp4" type="video/mp4">
        </video>
        <div class="container h-100">
            <div class="d-flex h-100 text-center align-items-center">
                <div class="w-100 text-white">
                    <h1 class="display-5" style="margin-top: 480px;">ÁREA DE ATENCIÓN</h1>
                    <h2 class="lead mb-3">PSICOLÓGICA DE LA <b>UTFV</b></h2>
                </div>
            </div>
        </div>
    </header>
</div>
<!-- Termina Video -->

<!-- Inicia Sección -->
<div class="containe-fluid">
    <div class="row m-0 p-0">
        <div class="col-md-12 parallax">
            <div class="container">
                <section class="my-5">
                    <div class="row">
                        <!-- Columna 1 -->
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-12 wow animate__animated animate__fadeIn">
                                    <img src="img/logoPsicologia.png" class="img-fluid" alt="logo Psicología UTFV">
                                    <br><br>
                                </div>
                                <div
                                    class="col-12 anuncio rounded py-3 wow animate__animated animate__bounceInLeft hvr-grow">
                                    <h3>Plática de inducción para pacientes de primera vez.</h3>
                                    <small class="text-muted"><em>Todos los lunes a las 11:00 am y 4:00 pm.</em></small>
                                    <img src="img/charla1erVez.png" class="img-fluid" alt="">
                                    <p>¡Bienvenidos a esta nueva etapa! Sabemos que comenzar un nuevo ciclo es
                                        emocionante y, a la vez, puede generar muchas preguntas. Por eso, hemos
                                        preparado esta plática de inducción para acompañarte en este inicio y brindarte
                                        toda la información que necesitas para tener un comienzo exitoso..</p>
                                </div>
                            </div>
                        </div>
                        <!-- Columna 1 -->
                        <!-- Columna 2 -->
                        <div class="col-md-4">
                            <div class="col-12 wow animate__animated animate__bounceInDown hvr-grow">
                                <h2>¿Cómo registrarme por primera vez?</h2>
                                <small class="text-muted"><em>Lunes 19 de Mayo 2025</em></small>
                                <p>¿Es tu primera visita? Mira este video y descubre cómo registrarte fácilmente para
                                    recibir atención psicológica.</p>
                            </div>
                            <div
                                class="col-12 anuncio rounded py-3 wow animate__animated animate__bounceInRight hvr-grow">
                                <h3>Plática “La importancia del cuidado de mis emociones”</h3>
                                <small class="text-muted"><em>Miércoles21 de Mayo 2025</em></small>
                                <img src="img/charla2.png" class="img-fluid" alt="">
                                <p>Las emociones son una parte fundamental de nuestra vida. Aprender a reconocerlas,
                                    comprenderlas y gestionarlas no solo mejora nuestro bienestar, sino que también
                                    fortalece nuestras relaciones y nos ayuda a enfrentar los desafíos diarios con mayor
                                    resiliencia.</p>
                            </div>
                        </div>
                        <!-- Columna 2 -->
                        <!-- Columna 3 -->
                        <div class="col-md-4 wow animate__animated animate__bounceInUp text-center mx-auto">
                              
                                <div class="fb-page" data-href="https://www.facebook.com/atenpsicologica.utfv/" data-tabs="timeline"
                                    data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                                </div>
                            
                        </div>
                        <div id="fb-root"></div>
                        <!-- Columna 3 -->
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<!-- Inicia Sección -->